# Generated by Django 5.1.2 on 2024-10-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_massagebox_receiver_alter_massagebox_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massagebox',
            name='room',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
