# Generated by Django 5.1.2 on 2024-10-30 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_remove_massagebox_room_delete_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagebox',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('receiv_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_recipient', to=settings.AUTH_USER_MODEL)),
                ('send_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_send', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatroom',
            },
        ),
    ]
