# Generated by Django 5.1.2 on 2024-10-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_massagebox_room_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
